//
//  Constants.swift
//  WordPressSimplify-iOS
//
//  Created by Diego Badaracco on 22/09/2022.
//

import Foundation

enum Constants {
    enum QueryParamNames {
        static let context = "context"
        static let page = "page"
        static let perPage = "per_page"
        static let search = "search"
        static let after = "after"
        static let before = "before"
        static let author = "author"
        static let authorExclude = "author_exclude"
        static let status = "status"
        static let taxRelation = "tax_relation"
        static let categories = "categories"
        static let categoriesExclude = "categories_exclude"
        static let tags = "tags"
        static let tagsExclude = "tags_exclude"
        static let sticky = "sticky"
        static let exclude = "exclude"
        static let include = "include"
        static let menuOrder = "menu_order"
        static let hideEmpty = "hide_empty"
        static let offset = "offset"
        static let order = "order"
        static let orderBy = "orderby"
        static let slug =  "slug"
        static let post =  "post"
        static let parent =  "parent"
        static let parentExclude = "parent_exclude"
        static let fields = "_fields"
        static let mimeType = "mime_type"
        static let mediaType = "media_type"
    }

    enum AllFields {
        static let id = "id"
        static let date = "date"
        static let dateGmt = "date_gmt"
        static let guid = "guid"
        static let link = "link"
        static let modified = "modified"
        static let modifiedGmt = "modified_gmt"
        static let slug = "slug"
        static let status = "status"
        static let type = "type"
        static let title = "title"
        static let author = "author"
        static let commentStatus = "comment_status"
        static let pingStatus = "ping_status"
        static let template = "template"
        static let altText = "alt_text"
        static let caption = "caption"
        static let description = "description"
        static let mediaType = "media_type"
        static let mimeType = "mime_type"
        static let mediaDetails = "media_details"
        static let post = "post"
        static let sourceUrl = "source_url"
        static let content = "content"
        static let excerpt = "excerpt"
        static let featuredMedia = "featured_media"
        static let format = "format"
        static let sticky = "sticky"
        static let categories = "categories"
        static let tags = "tags"
        static let count = "count"
        static let taxonomy = "taxonomy"
        static let name = "name"
        static let parent = "parent"
        static let menuOrder = "menu_order"
        static let username = "username"
        static let firstName = "first_name"
        static let lastName = "last_name"
        static let email = "email"
        static let url = "url"
        static let locale = "locale"
        static let nickname = "nickname"
        static let authorEmail = "author_email"
        static let authorName = "author_name"
        static let authorUrl = "author_url"
        static let authorAvatarUrls = "author_avatar_urls"
    }
}
